modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="ambidexterity"
version="1.20.1-1.0.0"
#logoFile="logo.png" #optional
displayName="Ambidexterity"
authors="Rinko1231"
description='''
Allows Attribute Modifiers for ISS StaffItems to take effect in either hand,
rather than being restricted to the main hand.
Includes a blacklist configurable via config/AmbidexterityConfig.toml.
'''